In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [2]:
data = [
    "When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"
]
df = pd.DataFrame(data = data, columns = ['sentence'])

In [4]:
from nlp_functions import nlp_pipeline
df['sentence_cleaned'] = nlp_pipeline(df['sentence'])

In [5]:
df

,sentence,sentence_cleaned
0,"When life gives you lemons, make lemonade! 🙂",life give lemon lemonade
1,She bought 2 lemons for $1 at Maven Market.,buy 2 lemon 1 maven market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],dozen lemon gallon lemonade
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemon lemon lemon lemon
4,He's running to the market to get a lemon — there's a great sale today.,s run market lemon s great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,maven market carry eureka lemon meyer lemon
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",arnold palmer half lemonade half ice tea
7,iced tea is my favorite,ice tea favorite

In [11]:
#DTM - Word Count Matrix
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
dtm = cv.fit_transform(df['sentence_cleaned'])
dtm_df = pd.DataFrame(data = dtm.toarray(), 
                      columns = cv.get_feature_names_out())

In [13]:
dtm_df[['lemon']]

   lemon
0      1
1      1
2      1
3      6
4      1
5      2
6      0
7      0

In [17]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer()
tfm = tv.fit_transform(df['sentence_cleaned'])
tfm_df = pd.DataFrame(data = tfm.toarray(), 
                      columns = tv.get_feature_names_out())
tfm_df

,arnold,buy,carry,dozen,eureka,favorite,gallon,give,great,half,...,lemonade,life,market,maven,meyer,palmer,run,sale,tea,today
0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.600547,0.000000,0.000000,...,0.434311,0.600547,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.63563,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.459683,0.532707,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.00000,0.000000,0.600547,0.000000,0.000000,0.600547,0.000000,0.000000,0.000000,...,0.434311,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.457738,0.000000,...,0.000000,0.000000,0.331033,0.000000,0.000000,0.000000,0.457738,0.457738,0.000000,0.457738
5,0.000000,0.00000,0.437511,0.000000,0.437511,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.316405,0.366668,0.437511,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.355161,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.710321,...,0.256850,0.000000,0.000000,0.000000,0.000000,0.355161,0.000000,0.000000,0.297652,0.000000
7,0.000000,0.00000,0.000000,0.000000,0.000000,0.644859,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.540443,0.000000

In [18]:
tfm_df[['lemon']]

      lemon
0  0.300100
1  0.317631
2  0.300100
3  1.000000
4  0.228737
5  0.437258
6  0.000000
7  0.000000